// <auto-generated />
using System;
using DataAccesLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccesLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220627154522_migProje")]
    partial class migProje
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Aboneler", b =>
                {
                    b.Property<int>("MailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MailDurum")
                        .HasColumnType("bit");

                    b.HasKey("MailID");

                    b.ToTable("abonelerss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Bildirimler", b =>
                {
                    b.Property<int>("BildirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BildirimDetaylari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BildirimDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("BildirimRengi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BildirimTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BildirimTuruSembol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BildirimID");

                    b.ToTable("bildirimlerss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BlogDurum")
                        .HasColumnType("bit");

                    b.Property<string>("BlogIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BlogOlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlogResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogUfakResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("YazarID")
                        .HasColumnType("int");

                    b.HasKey("BlogID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("YazarID");

                    b.ToTable("blogss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Hakkimda", b =>
                {
                    b.Property<int>("HakkimdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HakkimdaDetay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakkimdaDetay2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HakkimdaDurum")
                        .HasColumnType("bit");

                    b.Property<string>("HakkimdaLokasyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakkimdaResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakkimdaResim2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HakkimdaID");

                    b.ToTable("hakkimdass");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Iletisim", b =>
                {
                    b.Property<int>("IletisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IletisimAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IletisimDurum")
                        .HasColumnType("bit");

                    b.Property<string>("IletisimKonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimMesaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IletisimTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("IletisimID");

                    b.ToTable("ıletisimss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KategoriDurumu")
                        .HasColumnType("bit");

                    b.HasKey("KategoriID");

                    b.ToTable("kategoriss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Mesajlar", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlıcıMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GonderenMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MesajDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MesajTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesajın")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MesajID");

                    b.ToTable("mesajlarss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Mesajlar2", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlıcıMailID")
                        .HasColumnType("int");

                    b.Property<int?>("GonderenMailID")
                        .HasColumnType("int");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MesajDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MesajTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesajın")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MesajID");

                    b.HasIndex("AlıcıMailID");

                    b.HasIndex("GonderenMailID");

                    b.ToTable("mesajlarss2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Projeler", b =>
                {
                    b.Property<int>("ProjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjeAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("YazarID")
                        .HasColumnType("int");

                    b.HasKey("ProjeID");

                    b.HasIndex("YazarID");

                    b.ToTable("projelers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yazar", b =>
                {
                    b.Property<int>("YazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YazarAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YazarDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("YazarHakkinda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarSifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazarID");

                    b.ToTable("yazarss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yorumlar", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YorumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YorumBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YorumDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("YorumID");

                    b.HasIndex("BlogID");

                    b.ToTable("yorumlarss");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Kategori", "kategori")
                        .WithMany("blogs")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Yazar", "yazar")
                        .WithMany("blogs")
                        .HasForeignKey("YazarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategori");

                    b.Navigation("yazar");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Mesajlar2", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Yazar", "yazaralan")
                        .WithMany("yazaralici")
                        .HasForeignKey("AlıcıMailID");

                    b.HasOne("EntityLayer.Concrete.Yazar", "yazargonderen")
                        .WithMany("yazargonderici")
                        .HasForeignKey("GonderenMailID");

                    b.Navigation("yazaralan");

                    b.Navigation("yazargonderen");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Projeler", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Yazar", "yazar")
                        .WithMany("projelers")
                        .HasForeignKey("YazarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("yazar");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yorumlar", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Blog", "blog")
                        .WithMany("yorumlars")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.Navigation("yorumlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Kategori", b =>
                {
                    b.Navigation("blogs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yazar", b =>
                {
                    b.Navigation("blogs");

                    b.Navigation("projelers");

                    b.Navigation("yazaralici");

                    b.Navigation("yazargonderici");
                });
#pragma warning restore 612, 618
        }
    }
}
